docs: research on empty tile responses across map clients
linz/basemaps pull request #2831
Opened 2023-06-28 20:47 UTC by blacha

2023-07-03 22:36 UTC, Wentao-Kuang submitted a review, later dismissed

2023-07-05 02:52 UTC, ajacombs requested changes

2023-07-05 02:52 UTC, ajacombs commented on docs/api/empty-tiles.md
> +- ❌ HTTP RFC suggests that while valid servers "ought to return 204 No content"
```suggestion
- ❌ [HTTP RFC](https://www.rfc-editor.org/rfc/rfc9110.html#name-200-ok) suggests that while valid, servers "ought to return 204 No content"
```

2023-07-05 02:52 UTC, ajacombs commented on docs/api/empty-tiles.md
> +- ✔️ Supported by HTTP RFC "May return 0 byte 200"
```suggestion
- ✔️ Supported by [HTTP RFC](https://www.rfc-editor.org/rfc/rfc9110.html#name-200-ok), which allows 0 byte `200 Ok` responses as long as the message framing indicates this (via `Content-length=0` response header
```

2023-07-05 02:52 UTC, ajacombs commented on docs/api/empty-tiles.md
> +return HTTP 204 No Content with no body
```suggestion
Return HTTP `204 No Content`, with no body
```

2023-07-05 02:52 UTC, ajacombs commented on docs/api/empty-tiles.md
> +- ✔️ Supported in GIS ArcGIS/QGIS
```suggestion
- ✔️ Supported in ArcGIS Pro and QGIS
```

2023-07-05 02:52 UTC, ajacombs commented on docs/api/empty-tiles.md
> +- ✔️ Supported by LeafLet, OpenLayers
```suggestion
- ✔️ Supported by Leaflet and OpenLayers
```

2023-07-05 02:52 UTC, ajacombs commented on docs/api/empty-tiles.md
> +- ✔️ Supported by HTTP RFC "ought to return 204"
```suggestion
- ✔️ Supported by [HTTP RFC](https://www.rfc-editor.org/rfc/rfc9110.html#name-200-ok):  "server ought to return 204 No content"
```

2023-07-05 02:52 UTC, ajacombs commented on docs/api/empty-tiles.md
> +
```suggestion
```

2023-07-05 02:52 UTC, ajacombs commented on docs/api/empty-tiles.md
> +204 No content not always cached by browser
```suggestion
- Not always cached by browser
```

2023-07-05 02:52 UTC, ajacombs commented on docs/api/empty-tiles.md
> +- ❌ Is a error state
```suggestion
- ❌ Is an error state
```

2023-07-05 02:52 UTC, ajacombs commented on docs/api/empty-tiles.md
> +- ❌ Not always Cached, Browsers/CDN often ignore caching 404
```suggestion
- ❌ Not always cached: browsers / CDNs often do not cache 404 responses
```

2023-07-05 22:21 UTC, Wentao-Kuang approved these changes

2023-07-05 22:28 UTC, ajacombs approved these changes

2023-07-05 22:31 UTC, merged